add possibility to use action for multiple resources
telekom-mms/terratest-action pull request #15
Opened 2023-04-28 10:01 UTC by michaelamattes

2023-05-03 08:37 UTC, rndmh3ro requested changes

2023-05-09 12:42 UTC, michaelamattes commented on terratest/azure_test.go
> +				getAzureTestSetting := common.GetAzureTestSetting(function)
solved by https://github.com/telekom-mms/terratest-action/commit/54b975b372a8056528f863bc6c6804262dc5a46d

2023-05-10 09:14 UTC, rndmh3ro commented on README.md
> +  * explanation: a true / false boolean check if the resource could be created
```suggestion
  * description: check if the terraformresource was created. Returns true or false
```

2023-05-10 09:14 UTC, rndmh3ro commented on README.md
> +  * explanation: runs a terraform show of the created resource and checks if the conditions matches the conditions defined over `options`
```suggestion
  * description: runs a terraform show on the created resource and checks if the results matches the test-conditions defined in `options`
```

2023-05-10 09:21 UTC, rndmh3ro approved these changes

2023-05-10 09:22 UTC, merged